name: Deploy
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build artifact
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - name: Install dependencies
      run: |
        if [ -e yarn.lock ]; then
        yarn install --frozen-lockfile
        elif [ -e package-lock.json ]; then
        npm ci
        else
        npm i
        fi
    - name: Build
      run: npm run build
    - uses: actions/upload-artifact@v2
      with:
        name: build
        path: build
    - name: Pakage the build
      run: |
        cd build
        listaArchivos=`ls`
        zip -r ../SC-build.zip $listaArchivos
    - name: Copy the build to the EC2 instance
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key_path: "devops/cajitasdeamor.pem"
        source: "SC-build.zip"
        target: "/home/projects/builds"

  deploy:
    needs: [ build ]
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Deploy artifact
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key_path: "devops/cajitasdeamor.pem"
        script: |
          cd /home/projects/builds
          sudo mv SC-build.zip /var/www/html/buscador
          cd /var/www/html/buscador
          sudo unzip -o SC-build.zip
          sudo rm SC-build.zip
          sudo systemctl restart nginx
    


